/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppChannelsRouteImport } from './routes/_app/channels'
import { Route as AppChannelsIndexRouteImport } from './routes/_app/channels.index'
import { Route as AppChannelsChannelIdRouteImport } from './routes/_app/channels.$channelId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsIndexRoute = AppChannelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChannelsRoute,
} as any)
const AppChannelsChannelIdRoute = AppChannelsChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => AppChannelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/channels': typeof AppChannelsRouteWithChildren
  '/channels/$channelId': typeof AppChannelsChannelIdRoute
  '/channels/': typeof AppChannelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/channels/$channelId': typeof AppChannelsChannelIdRoute
  '/channels': typeof AppChannelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/channels': typeof AppChannelsRouteWithChildren
  '/_app/channels/$channelId': typeof AppChannelsChannelIdRoute
  '/_app/channels/': typeof AppChannelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/channels'
    | '/channels/$channelId'
    | '/channels/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/channels/$channelId' | '/channels'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/channels'
    | '/_app/channels/$channelId'
    | '/_app/channels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/channels': {
      id: '/_app/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/': {
      id: '/_app/channels/'
      path: '/'
      fullPath: '/channels/'
      preLoaderRoute: typeof AppChannelsIndexRouteImport
      parentRoute: typeof AppChannelsRoute
    }
    '/_app/channels/$channelId': {
      id: '/_app/channels/$channelId'
      path: '/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof AppChannelsChannelIdRouteImport
      parentRoute: typeof AppChannelsRoute
    }
  }
}

interface AppChannelsRouteChildren {
  AppChannelsChannelIdRoute: typeof AppChannelsChannelIdRoute
  AppChannelsIndexRoute: typeof AppChannelsIndexRoute
}

const AppChannelsRouteChildren: AppChannelsRouteChildren = {
  AppChannelsChannelIdRoute: AppChannelsChannelIdRoute,
  AppChannelsIndexRoute: AppChannelsIndexRoute,
}

const AppChannelsRouteWithChildren = AppChannelsRoute._addFileChildren(
  AppChannelsRouteChildren,
)

interface AppRouteChildren {
  AppChannelsRoute: typeof AppChannelsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppChannelsRoute: AppChannelsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
